### ISSUE TITLE
No attribute default

### ISSUE THREAD

**Issue by alxnegrila** [keyphact/pgoapi#26]
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "pgoapi/pgoapi/rpc_api.py", line 50, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/lib/python2.7/site-packages/google/protobuf/symbol_database.py", line 164, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'

**Comment by chaipokoi** [comment]
Did you installed all the requirements ? :)

https://github.com/keyphact/pgoapi/blob/master/requirements.txt

**Comment by alxnegrila** [comment]
Yes, I did...

**Comment by ProLoDs** [comment]
you are using the wrong protobuf version. 
try `pip install protobuf`

**Comment by alxnegrila** [comment]
Worked. Thanks...

**Comment by abhishekagarwal21** [comment]
@ProLoDs : It works....Thanks a lot!
