### ISSUE TITLE
what did i miss ? 

### ISSUE THREAD

**Issue by axman18** [keyphact/pgoapi#40]
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "C:\Users\Alex\Downloads\PokemonGo-Bot\pgoapi\pgoapi.py", line 122, in function
    return request.call()
  File "C:\Users\Alex\Downloads\PokemonGo-Bot\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "C:\Users\Alex\Downloads\PokemonGo-Bot\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by xssc** [comment]
Not all required files are included in this repository

**Comment by axman18** [comment]
ah so I need to install more things thanks ^^
