### ISSUE TITLE
cffi version mismatch?

### ISSUE THREAD

**Issue by jjordantb** [keyphact/pgoapi#46]
Reproduce:
If I reinstall python3.5, everything works and runs okay, I then have to reinstall ubuntu-desktop, and then I get this error again.

Using ubuntu 16.04 x64
Python 3.5.2

Traceback (most recent call last):
  File "/home/jjordan/PycharmProjects/PokeBuddy/src/application.py", line 4, in <module>
    import pgoapi
  File "/usr/local/lib/python3.5/dist-packages/pgoapi-1.1.6-py3.5.egg/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python3.5/dist-packages/pgoapi-1.1.6-py3.5.egg/pgoapi/pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "/usr/local/lib/python3.5/dist-packages/pgoapi-1.1.6-py3.5.egg/pgoapi/auth_google.py", line 33, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "/usr/local/lib/python3.5/dist-packages/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/usr/local/lib/python3.5/dist-packages/gpsoauth/google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "/usr/local/lib/python3.5/dist-packages/Cryptodome/PublicKey/RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "/usr/local/lib/python3.5/dist-packages/Cryptodome/IO/PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "/usr/local/lib/python3.5/dist-packages/Cryptodome/IO/_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "/usr/local/lib/python3.5/dist-packages/Cryptodome/Cipher/__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python3.5/dist-packages/Cryptodome/Cipher/_mode_ecb.py", line 29, in <module>
    from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python3.5/dist-packages/Cryptodome/Util/_raw_api.py", line 39, in <module>
    ffi = FFI()
  File "/usr/local/lib/python3.5/dist-packages/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.5.2 != 1.7.0

**Comment by elliottcarlson** [comment]
Make sure pip is up to date, and `apt-get install python-cffi` can get you up to date with cffi.

**Comment by jjordantb** [comment]
@elliottcarlson both are up to date

**Comment by cheesynoob** [comment]
Your version is 1.7.0, the backend is 1.5.2 use pip install --upgrade python-cffi==1.5.2 to match up. You would be better off using a virtual environment though as ubuntu wants 1.7

**Comment by jjordantb** [comment]
@cheesynoob its apperently cffi instead of python-cffi but it worked thanks!

**Comment by JingYuan0818** [comment]
@cheesynoob  I use your way, but it reports:

Collecting python-cffi==1.5.2
  Could not find a version that satisfies the requirement python-cffi==1.5.2 (from versions: )
No matching distribution found for python-cffi==1.5.2

How can i solve it?
