### ISSUE TITLE
Get_map_objects() sometimes raises IndexError

### ISSUE THREAD

**Issue by Wouter93** [keyphact/pgoapi#47]
Sometimes, when using get_map_objects(), you get a dictionary back containing 'api_url' and 'auth_ticket'.

This wouldn't be so bad, except that it also causes an IndexError in rpc_api (_parse_sub_responses())

Example dictionary response:
```
Response dictionary (get_map_objects):
{   'api_url': u'pgorelease.nianticlabs.com/plfe/91',
    'auth_ticket': {   'end': 'HOIAGtMderProabH98FTQA==',
                       'expire_timestamp_ms': 1470612830988L,
                       'start': 'Ko8EZronBJEfhyUJMIICjve/9mpK59Cy301qmd5Wl/DERPx14+ffm7QKBayA2BIwF6w4d6gVSgrYbHEeGBZ1hnu8l+bzyfShXm8KAllq+r4='}
,
    'request_id': 311523737411100314L,
    'responses': {   'GET_MAP_OBJECTS': {   'map_cells': [   {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455928213864448L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455936803799040L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455930361348096L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455943246249984L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455945393733632L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455938951282688L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455941098766336L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455969016053760L},
                                                             {   'current_timestamp_ms': 1470617030988L,
                                                                 's2_cell_id': 5170455966868570112L}],
                                            'status': 1}},
    'status_code': 2}
```

**Comment by elliottcarlson** [comment]
Can you provide a trace of the error, don't see anything immediately wrong.

**Comment by Wouter93** [comment]
```
list index out of range
Full stacktrace:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 474, in scanPokemon
    response_dict = api.get_map_objects(latitude =coords[0], longitude = coords[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "/home/pokemap/pgoapi/pgoapi.py", line 129, in function
    return request.call()
  File "/home/pokemap/pgoapi/pgoapi.py", line 231, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/pokemap/pgoapi/rpc_api.py", line 140, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/pokemap/pgoapi/rpc_api.py", line 376, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/home/pokemap/pgoapi/rpc_api.py", line 394, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range
```

**Comment by elliottcarlson** [comment]
Hmm - I'm a little confused - the final line from the trace says that line is at 394, but in the current repo, that would be line 376;

Anyhow - you might be right about the extra fields; I assume (without testing, just a cursory glance at the code) that when those fields are returned, they are being passed in to `_parse_sub_responses`; but since they are not response fields they cause the error. I believe that clearing out those fields when present (potentially when a new auth ticket is being renewed, https://github.com/keyphact/pgoapi/blob/249d3be7fbbdabc7f9adea17cbc899d6549e47a2/pgoapi/rpc_api.py#L156) then it could prevent the error.

**Comment by Kieken72** [comment]
Have the same issue here with pokeminer, Some forts always return the error. Others don't.
`Traceback (most recent call last):
  File "worker.py", line 129, in run
    self.main()
  File "worker.py", line 166, in main
    cell_id=cell_ids
  File "..\src\pgoapi\pgoapi\pgoapi.py", line 122, in function
    return request.call()
  File "..\src\pgoapi\pgoapi\pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "..\src\pgoapi\pgoapi\rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "..\src\pgoapi\pgoapi\rpc_api.py", line 359, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "..\src\pgoapi\pgoapi\rpc_api.py", line 376, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range`

**Comment by justMaku** [comment]
@maintainers:
If server replies with status `53` you're supposed to take new api url and redo the request to that endpoint.
