### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aididhaiqal** [keyphact/pgoapi#7]
```
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "C:\Users\aidid\Desktop\Work\Unknown6-PGOAPI\pgoapi\pgoapi.py", line 121, in function
    return request.call()
  File "C:\Users\aidid\Desktop\Work\Unknown6-PGOAPI\pgoapi\pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "C:\Users\aidid\Desktop\Work\Unknown6-PGOAPI\pgoapi\rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

Any idea what happend?

**Comment by checkplys** [comment]
Did you try to update to the unknow6 fix?

**Comment by Corlobin** [comment]
Same here

**Comment by xssc** [comment]
Do you have all the required files. See: https://github.com/keyphact/pgoapi/blob/917bff081a2ec88b4d47b4aba4e1131d4b318ee9/pokecli.py

**Comment by aididhaiqal** [comment]
Yes i have encrypt.dll and it giving me this error now
2016-08-07 11:28:10,747 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "C:\Users\aidid\Desktop\Work\test-unknown6\pgoapi\pgoapi.py", line 121, in function
    return request.call()
  File "C:\Users\aidid\Desktop\Work\test-unknown6\pgoapi\pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "C:\Users\aidid\Desktop\Work\test-unknown6\pgoapi\rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by Corlobin** [comment]
I just cloned this repo and executed the pokecli. What am I doing wrong?

**Comment by xssc** [comment]
@Corlobin do you have all required files? see:  https://github.com/keyphact/pgoapi/blob/917bff081a2ec88b4d47b4aba4e1131d4b318ee9/pokecli.py

**Comment by aididhaiqal** [comment]
@xssc  I get my encrypt.dll from https://github.com/PokemonGoMap/PokemonGo-Map/

**Comment by Corlobin** [comment]
Hi, xssc. I think I do. Where I see the encrypt.dll?

**Comment by aididhaiqal** [comment]
@Corlobin You need to download it...It not come prebundled

**Comment by xssc** [comment]
@Corlobin Not all required files are included in this repo.

**Comment by aididhaiqal** [comment]
@xssc  any idea for the issue?With the same dll,PokemonGoMap give me this  `2016-08-07 11:43:23,861 [ search_worker_0][        search][ WARNING] Exception while downloading map: [Error 126] The specified module could not be found`
and pokecli give me `2016-08-07 11:44:18,221 [  auth_ptc] [ INFO] PTC User Login successful.
2016-08-07 11:44:18,223 [  auth_ptc] [ INFO] Request PTC Access Token...
2016-08-07 11:44:18,641 [  auth_ptc] [ INFO] PTC Access Token successfully retrieved.
2016-08-07 11:44:18,653 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-07 11:44:18,653 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "C:\Users\aidid\Desktop\Work\test-unknown6\pgoapi\pgoapi.py", line 121, in function
    return request.call()
  File "C:\Users\aidid\Desktop\Work\test-unknown6\pgoapi\pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "C:\Users\aidid\Desktop\Work\test-unknown6\pgoapi\rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application`

**Comment by xssc** [comment]
No idea right now, looking into it

**Comment by Corlobin** [comment]
Working fine here after I downloaded the encrypt.dll.

**Comment by xssc** [comment]
@aididhaiqal are you on a 32bit windows?

**Comment by DangerousHIV** [comment]
can any1 point me in the direction to download the new file update

**Comment by aididhaiqal** [comment]
64 Bit

**Comment by blackhattristar** [comment]
Can anyone help me? What am I doing wrong? I download this repo, install requirements.txt, throw the encrypt.dll in there from [Here](https://github.com/PokemonGoMap/PokemonGo-Map/) and then enter this command in my terminal `python pokecli.py -a google -u@gmail.com -p -l “NewYork“` and I get this in return `2016-08-06 20:50:34,726 [ utilities] [ INFO] Coordinates (lat/long/alt) for location: 40.7127837 -74.0059413 0.0
2016-08-06 20:50:34,726 [auth_google] [ INFO] Google User Login for:@gmail.com
2016-08-06 20:50:35,514 [auth_google] [ INFO] Google User Login successful.
2016-08-06 20:50:35,514 [auth_google] [ INFO] Request Google Access Token...
2016-08-06 20:50:35,683 [auth_google] [ INFO] Google Access Token successfully received.
2016-08-06 20:50:35,697 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-06 20:50:35,697 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "/Users//Downloads/pgoapi-master/pgoapi/pgoapi.py", line 121, in function
    return request.call()
  File "/Users//Downloads/pgoapi-master/pgoapi/pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "/Users//Downloads/pgoapi-master/pgoapi/rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt.dll, 6): no suitable image found.  Did find:
	encrypt.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00`

Please help.

**Comment by DangerousHIV** [comment]
idk where ur getting this ahaha

**Comment by blackhattristar** [comment]
What am I doing wrong? There are no steps in the wiki.

**Comment by Corlobin** [comment]
Download this file https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/encrypt.dll and put in pogoapi/ folder

**Comment by DangerousHIV** [comment]
hmmm cant seem to find that folder or the old one

**Comment by blackhattristar** [comment]
@Corlobin What command do you run in the terminal? Is this ok? `python pokecli.py -a google -u@gmail.com -p -l “NewYork“`?

**Comment by blackhattristar** [comment]
I keep getting stuck at get_map_objects or something:

`2016-08-06 21:03:45,264 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "/Users//Downloads/pgoapi-master/pgoapi/pgoapi.py", line 121, in function
    return request.call()
  File "/Users//Downloads/pgoapi-master/pgoapi/pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "/Users//Downloads/pgoapi-master/pgoapi/rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt.dll, 6): image not found`

**Comment by blackhattristar** [comment]
@xssc Where does all the code go?

**Comment by rbryson74** [comment]
The current DLL is windows 32bit
Make sure to use Python 2.7 32bit

**Comment by xssc** [comment]
@rbryson74  is correct

**Comment by blackhattristar** [comment]
Where do I get that?

**Comment by DangerousHIV** [comment]
anyway someone can post a step solution and links on how to fix this please and thank you

**Comment by xssc** [comment]
https://www.python.org/downloads/windows/ @blackhattristar  @DangerousHIV @aididhaiqal The 32bit is x86, NOT x86-64

**Comment by blackhattristar** [comment]
@xssc I'm using a Mac. How can I get this to work on Mac?

**Comment by pbdeuchler** [comment]
`encrypt.dll` needs to be in the same directory as where you are _running_ the code, not where the pgoapi code is. For instance, if you are running the examples from the `examples` folder then your `encrypt.dll` file needs to be in the `examples` folder. If you are calling the pgoapi code yourself you can also specify your own path with the `activate_signature(lib_path)` method on the `RpcApi` class.

Obviously this does not apply to those with architecture mismatches.

**Comment by Kliffe** [comment]
Hello everybody! I have an stupid question :p (Btw im from Poland so sorry for my english) How did I instal this? :)

**Comment by xssc** [comment]
@blackhattristar macs don't use dll, they use so

**Comment by blackhattristar** [comment]
@xssc How do I get this going on mac then?

**Comment by DangerousHIV** [comment]
what is python for

**Comment by blackhattristar** [comment]
Where can I find the required files to get this going on Mac?

**Comment by blackhattristar** [comment]
@xssc Where can I find the required files to get this going on Mac? Any help would be greatly appreciated!

**Comment by DangerousHIV** [comment]
@blackhattristar i think we are stuck in the loop man anyone who has it working wont show us how to get it working pretty sad not a very helpfull community

**Comment by xssc** [comment]
This issue is mis-matching architecture for python and dlls. This is not a tutorial forum. If you are trying to use a 32bit dll, you need 32bit python (x86): https://www.python.org/downloads/windows/

**Comment by blackhattristar** [comment]
I don't want to use the 32bit dll method because I have a mac. I don't have windows.

**Comment by blackhattristar** [comment]
@xssc I'm just asking, if you know how to get this going on mac and you were nice enough to tell me, and I'm sure all the other people who need to know, it would be greatly appreciated.

**Comment by xssc** [comment]
@blackhattristar This issue is related to windows. And we do not provide all required files for specific operating systems in this repo.

**Comment by blackhattristar** [comment]
@xssc You don't know where the required files for mac are located?

**Comment by DangerousHIV** [comment]
@xssc if this isnt a tut fourm can you point me to one ahahah im just trying to get this working

**Comment by blackhattristar** [comment]
@DangerousHIV I couldn't agree more!

**Comment by Mavrik435** [comment]
I keep getting this error can anyone please tell me what this is and how to fix please. thank you.
WindowsError: [Error 126] The specified module could not be found

**Comment by xssc** [comment]
@DangerousHIV @blackhattristar This is very new, I don't know of any tutorials for this

**Comment by xssc** [comment]
@Mavrik435 Make sure you have all required files, they are not all in this repo

**Comment by Mavrik435** [comment]
@xssc  is it another master maps download I need?

**Comment by smokeinggta** [comment]
No offense guys, these guys are just getting the coding together. Give them time to work their magic. Thank you for all your work. :-)

**Comment by DangerousHIV** [comment]
@xssc could you possible make one.....that would be outstanding and if you do all this the bot works again yes and will there ever be a direct download so you dont have to do all this

**Comment by xssc** [comment]
@aididhaiqal have you resolved this issue by installing 32bit python?

**Comment by aididhaiqal** [comment]
Yep,Solved

**Comment by Ephemerality** [comment]
Not working here after installing 32bit Python.  
`Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32`  
`ImportError: DLL load failed: %1 is not a valid Win32 application.`

**Comment by Mavrik435** [comment]
Any chance anyone could tell me where to get all of the files so I can get this going for myself please. Thank you so much, appreciate all the work you guys have done

**Comment by blackhattristar** [comment]
@DangerousHIV I'll order someone a pizza if they can show us how to get it running for mac? Lol

**Comment by OhhPian** [comment]
Which files do i need to download ? quite confusing here ._.
